apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: sketchme
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sketchme
    spec:
      containers:
      - name: sketchme
        image: index.docker.io/user1m/sketchme
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: sketchme
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
  selector:
    app: sketchme